version: "3.8"

services:
  excel-auto-etl:
    build: .
    container_name: excel_auto_etl
    restart: unless-stopped
    mem_limit: 32g
    memswap_limit: 32g     # = sin swap adicional
    volumes:
      - .:/app
      - excelautoetl_node_modules:/app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - "9229:9229"

volumes:
  excelautoetl_node_modules: